[tool-chain]
solana-version = "2.3.0"
anchor_version = "0.32.1"

[features]
seeds = false
resolution = true

[features.devnet]
amm_v3 = ["devnet"]

[programs.devnet]
amm_v3 = "FNJHxG95pChntXLTzBxdCPdgcA4iPsjHpJBHPJXmNN28"

[registry]
url = "https://github.com/raydium-io/raydium-amm-v3"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
