[tool-chain]
solana-version = "2.3.0"
anchor_version = "0.32.1"

[features]
seeds = false
resolution = true

[features.devnet]
amm_v3 = ["devnet"]

[programs.mainnet]
amm_v3 = "CftvdSTmVaaXg4YGKhuCCWo2uPhd9RTY35JyyKqadXnX"

[programs.devnet]
amm_v3 = "8kpocpzq5VVz1FbNNCmpb72j8apf8dFb7XsJfYUdCmiC"

[registry]
url = "https://github.com/raydium-io/raydium-amm-v3"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
